# Generated by Django 2.0.1 on 2018-08-03 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=200)),
                ('video', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Courses.Course')),
            ],
        ),
        migrations.RemoveField(
            model_name='lab',
            name='course_id',
        ),
        migrations.AddField(
            model_name='lab',
            name='topic_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Courses.CourseTopic'),
            preserve_default=False,
        ),
    ]
