# Generated by Django 2.0.7 on 2018-08-04 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0002_auto_20180803_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labtasks',
            name='lab_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Courses.CourseTopic'),
        ),
    ]
