# Generated by Django 2.0.1 on 2018-08-08 01:03

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0004_remove_lab_topic_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('image_one', models.FileField(blank=True, null=True, upload_to='')),
                ('text_one', models.CharField(blank=True, max_length=200, null=True)),
                ('image_two', models.FileField(blank=True, null=True, upload_to='')),
                ('text_two', models.CharField(blank=True, max_length=200, null=True)),
                ('image_three', models.FileField(blank=True, null=True, upload_to='')),
                ('text_three', models.CharField(blank=True, max_length=200, null=True)),
                ('slug', models.SlugField(blank=True, default='', max_length=40)),
            ],
        ),
    ]
